### ISSUE TITLE
dlopen: image not found

### ISSUE THREAD

**Issue by redperadot** [darkgem-io/simple-random#1]
When loading the shared library from within the gem, the fallowing error occurs:

```
LoadError: Could not open library '/Users/goldperadot/Projects/gems/ext/simple_random.so': dlopen(/Users/goldperadot/Projects/gems/ext/simple_random.so, 5): image not found
	from /Users/goldperadot/.rvm/gems/ruby-2.2-head/gems/ffi-1.9.8/lib/ffi/library.rb:133:in `block in ffi_lib'
	from /Users/goldperadot/.rvm/gems/ruby-2.2-head/gems/ffi-1.9.8/lib/ffi/library.rb:100:in `map'
	from /Users/goldperadot/.rvm/gems/ruby-2.2-head/gems/ffi-1.9.8/lib/ffi/library.rb:100:in `ffi_lib'
	from lib/simple-random.rb:5:in `<class:SimpleRandom>'
	from lib/simple-random.rb:3
	from /Users/goldperadot/.rvm/rubies/ruby-2.2-head/bin/irb:11:in `<main>'
```

Referencing the library from it's install directory, all is good. So it must be referring to something around that directory.

**Comment by redperadot** [comment]
I figured out that shared libraries must start with 'lib' and be in '/usr/local/lib', my bad---whoops. So now I just have the gem copy it from self if it doesn't exist.
